/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InformacjeRouteImport } from './routes/informacje'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PozRouteImport } from './routes/poz'
import { Route as SpecjalisciRouteImport } from './routes/specjalisci'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacjeRoute = InformacjeRouteImport.update({
  id: '/informacje',
  path: '/informacje',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PozRoute = PozRouteImport.update({
  id: '/poz',
  path: '/poz',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecjalisciRoute = SpecjalisciRouteImport.update({
  id: '/specjalisci',
  path: '/specjalisci',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/informacje': typeof InformacjeRoute
  '/kontakt': typeof KontaktRoute
  '/poz': typeof PozRoute
  '/specjalisci': typeof SpecjalisciRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/informacje': typeof InformacjeRoute
  '/kontakt': typeof KontaktRoute
  '/poz': typeof PozRoute
  '/specjalisci': typeof SpecjalisciRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/informacje': typeof InformacjeRoute
  '/kontakt': typeof KontaktRoute
  '/poz': typeof PozRoute
  '/specjalisci': typeof SpecjalisciRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/informacje' | '/kontakt' | '/poz' | '/specjalisci'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/informacje' | '/kontakt' | '/poz' | '/specjalisci'
  id: '__root__' | '/' | '/informacje' | '/kontakt' | '/poz' | '/specjalisci'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InformacjeRoute: typeof InformacjeRoute
  KontaktRoute: typeof KontaktRoute
  PozRoute: typeof PozRoute
  SpecjalisciRoute: typeof SpecjalisciRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacje': {
      id: '/informacje'
      path: '/informacje'
      fullPath: '/informacje'
      preLoaderRoute: typeof InformacjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poz': {
      id: '/poz'
      path: '/poz'
      fullPath: '/poz'
      preLoaderRoute: typeof PozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specjalisci': {
      id: '/specjalisci'
      path: '/specjalisci'
      fullPath: '/specjalisci'
      preLoaderRoute: typeof SpecjalisciRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InformacjeRoute: InformacjeRoute,
  KontaktRoute: KontaktRoute,
  PozRoute: PozRoute,
  SpecjalisciRoute: SpecjalisciRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
